# database init, supports mysql too
database: h2

spring:
  datasource:
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging
logging:
  level:
    org.springframework: warn
    io.geekshop: warn
    graphql: error
    # https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/432
    notprivacysafe.graphql: warn

geekshop:
  company-name: ${COMPANY_NAME:GEEKSHOP}
  auth-options:
    disable-auth: ${DISABLE_AUTH:false}
    token-method: ${TOKEN_MEHTOD:cookie}
    cookie-options:
      http-only: ${COOKIE_HTTP_ONLY:true}
    auth-token-header-key: ${AUTH_TOKEN_HEADER_KEY:geekshop-shared-token}
    session-duration: ${SESSION_DURATION:1y}
    session-cache-ttl: ${SESSION_CACHE_TTL:300}
    require-verification: ${REQUIRE_VERIFICATION:true}
    verification-token-duration: ${VERIFICATION_TOKEN_DURATION:7d}
    superadmin-credentials:
      identifier: ${SUPERADMIN_IDENTIFIER:superadmin}
      password: ${SUPADMIN_PASSWORD:superadmin123}

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
